export const apiEndpoints = {
  addOriginFamilyMember: "familyTree/add/origin",
  updateFamilyMember: "familyTree/update",
  addFamilyMember: "familyTree/add",
  deleteFamilyMember: "familyTree/delete",
  familyLogin: "familyTree/enter",
  getFamilyDetails: "familyTree/getDetails",
  uploadImage: "upload",
  downloadImage: "download",
  authLink: "auth/getLink",
  logout: "auth/logout",
  token: "auth/token",
  login: "auth/login",
  getData: "auth/getData",
  signIn: "auth/signIn",
  signUp: "auth/signUp",
  emailValidity: "auth/register_email",
};
